# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-20 01:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitysubfieldeffects',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='activitysubfieldeffects',
            name='subfield',
        ),
        migrations.RemoveField(
            model_name='subfields',
            name='field',
        ),
        migrations.RemoveField(
            model_name='usersubfields',
            name='subfield',
        ),
        migrations.RemoveField(
            model_name='usersubfields',
            name='user',
        ),
        migrations.AddField(
            model_name='fields',
            name='subfieldOf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.Fields'),
        ),
        migrations.DeleteModel(
            name='ActivitySubfieldEffects',
        ),
        migrations.DeleteModel(
            name='Subfields',
        ),
        migrations.DeleteModel(
            name='UserSubfields',
        ),
    ]
